from justrelax.node.holographic_menu.service import VideoPlayer
from justrelax.node.holographic_menu.vlc_player import VLCVideoPlayer
from justrelax.node.holographic_menu.vlc_player import VLCLoopingChapterVideoPlayer
