version: 1
disable_existing_loggers: true

root:
  level: DEBUG
  handlers: [console, justrelax]
  propagate: yes

formatters:
  standard:
    format: "[%(asctime)s][%(levelname)s] %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  justrelax:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /dev/null
    maxBytes: 10485760 # 10MB
    backupCount: 10
    encoding: utf8
